title: Email Conversion Add-On
description: When provided a public Google Drive or Dropbox link, it will download the EML/MSG files in the link, convert them to PDF, and upload them to DocumentCloud. Email attachments will be presented for download as a zip file.
type: object
documents: []
properties:
 url:
    title: URL
    type: string
    format: uri
    description: A publicly accessible Google Drive or Dropbox folder or file. 
 attachments:
    title: Attempt Attachment Extraction
    type: boolean
 access_level:
    title: Access level for uploaded documents (public, private(default), organization)
    type: string
    default: private
 project_id:
    title: Project ID of the project you would like the documents uploaded to (optional)
    type: integer
required: 
  - url
